// DO NOT EDIT. This file is generated by deno.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running dev.ts

import { Handler } from "$types/routes.ts";
import $0 from "./routes/v1/my-name/[name].ts";
import $1 from "./routes/v1/index.ts";
import $2 from "./routes/v2/my-name/[name].ts";
import $3 from "./routes/v2/my-name/index.ts";
import $4 from "./routes/v2/kaju.ts";
import $5 from "./routes/v2/index.ts";
import $6 from "./routes/hlo.ts";
import $7 from "./routes/index.ts"

export type ROUTES = {
	"/v1/my-name/:name": Handler;
	"/v1": Handler;
	"/v2/my-name/:name": Handler;
	"/v2/my-name": Handler;
	"/v2/kaju": Handler;
	"/v2": Handler;
	"/hlo": Handler;
	"/": Handler;
};

export type Manifest = {
	routes: ROUTES;
	baseUrl: string;
};

const manifest: Manifest = {
	routes: {
		"/v1/my-name/:name": $0,
		"/v1": $1,
		"/v2/my-name/:name": $2,
		"/v2/my-name": $3,
		"/v2/kaju": $4,
		"/v2": $5,
		"/hlo": $6,
		"/": $7
	},
	baseUrl: import.meta.url,
};

export default manifest;
